### ISSUE TITLE
Beta 6 Release Checklist

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#291]
- [x] Document new feature layer events
- [x] Document query for map/image service
- [x] Final Tests
- [x] Final Build
- [x] Update Build Sizes
- [x] Build Site
- [x] Test Examples
- [x] Deploy Site
