### ISSUE TITLE
FeatureLayer Performance Enhancements

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#3]
This issue collects ideas for improving the performance of `L.esri.FeatureLayer`.
- [x] #12 Gridded queries for FeatureLayer
- [x] #14 Investigate performance difference of hiding feature vs removing them.
- [x] #13 Simplify polygons and polylines based on zoom.
- [ ] #15 Option to run the processing code in a web worker for extra performance

Many ideas were inspired by https://speakerdeck.com/mourner/high-performance-data-visualizations and conversations with @swingley on the ArcGIS Javascript API
