### ISSUE TITLE
RC 5 Docs and Changelog checklist

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#430]
* [x] Document `cacheLayers` option on `FeatureLayer`
* [x] Document `minZoom`, `maxZoom` on `FeatureLayer`
* [x] Document change to `Task` contructors
* [x] Update change log with all changes since last release
