### ISSUE TITLE
2.0.0 Checklist

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#571]
###### Build system

* [x] New build system based on https://github.com/Esri/esri-leaflet/tree/es6 + Esparanto
* [x] New system for custom builds based on https://github.com/rollup/rollup
* [x] Move to https://github.com/ngoldman/gh-release for release automation
* [ ] New JSPM example

###### Testing

* [x] Figure out code coverage with ES 6 modules https://medium.com/@gunnarlium/es6-code-coverage-with-babel-jspm-karma-jasmine-and-istanbul-2c1918c5bb23
* [x] Test the new `setStyle`, `resetStyle`, `setFeatureStyle` and `resetFeatureStyle`
* [x] Test passing `renderer` through in `FeatureLayer`
* [x] Test passing `pane` through in `FeatureLayer` and `RasterLayer`
* [x] Test placing labels on top of Polygons and Polylines by default

**Comment by patrickarlt** [comment]
Tests (with code coverage) are working! But some are failing.

**Comment by patrickarlt** [comment]
@jgravois closing this. I want to get the geocoder to 2.0 also before launching the site.
