### ISSUE TITLE
2.0.0-beta.7 release steps

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#703]
- [x] wrap up breaking out new dependencies #652
- [X] tag [`1.0.1`](https://github.com/patrickarlt/leaflet-virtual-grid/issues/8) of leaflet-virtual-grid on npm and bump dependency here 4cb00dc
- [X] bump changelog aa712e1
- [x] bump `package.json` and `bower.json` version numbers
- [x] tag `2.0.0-beta.7` on github and publish to npm
- [x] confirm release made it to [jsdelivr](http://www.jsdelivr.com/projects/leaflet.esri)
- [X] update [download](http://esri.github.io/esri-leaflet/download/) page urls 594400b
- [x] publish website updates to `gh-pages` (i don't think we're waiting on anything besides #701 and swapping back in the CDN source code reference)
- [ ] figure out why `npm install` lays down `1.0.2`

**Comment by jgravois** [comment]
is there anything you want me to hold back on before tagging the release and pushing the updated website @patrickarlt?

**Comment by patrickarlt** [comment]
@jgravois no go for it.

**Comment by jgravois** [comment]
for some reason, even though npmjs.org shows `2.0.0-beta.7` as the latest version, running `npm install esri-leaflet` manually is lays down `1.0.2` on my machine.

when i published `1.0.2` a few minutes before, i intentionally specified `npm publish --tags old` so that it wouldn't be tagged `latest`.

so strange.

**Comment by jgravois** [comment]
not sure how, but the problem has mysteriously disappeared.  must have been the :smiling_imp:s
