### ISSUE TITLE
2.0.0 release checklist

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#775]
- [x] merge #772, #774 
- [x] merge patrickarlt/leaflet-virtual-grid/pull/11
  - [x] tag, bag `1.0.4`
  - [x] bump dependency here
  - [x] confirm resolution of problem reported on [gis.se](http://gis.stackexchange.com/questions/190545/esri-leaflet-feature-layer-toggle-question)
- [x] test all samples in chrome, IE9
- [x] fix #776
- [x] bump/update changelog
- [x] bump `package.json`~~, `src/`,~~ and `bower.json` to `2.0.0`
- [x] publish on github/npm
- [x] confirm that jsdelivr picked up the new version
  - [x] bump versions on doc site
  - [x] deploy doc updates 

optional:
- [ ] #773
